language: r

sudo: required

before_install:
  cd ./rangeBuilder

r_binary_packages:
  - rgdal
  - sp
  - raster
  - stringi
  - rgeos

r_packages:
  - alphahull

after_script:
 - ./travis-tool.sh dump_logs
